# Generated by Django 3.1.2 on 2022-03-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('small_small_hr', '0012_auto_20220305_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAnnualLeave',
            fields=[
                ('annualleave_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.annualleave')),
            ],
            options={
                'abstract': False,
            },
            bases=('small_small_hr.annualleave',),
        ),
        migrations.CreateModel(
            name='EFreeDay',
            fields=[
                ('freeday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.freeday')),
            ],
            bases=('small_small_hr.freeday',),
        ),
        migrations.CreateModel(
            name='ELeave',
            fields=[
                ('leave_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.leave')),
            ],
            options={
                'abstract': False,
            },
            bases=('small_small_hr.leave',),
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.role')),
            ],
            options={
                'abstract': False,
            },
            bases=('small_small_hr.role',),
        ),
        migrations.CreateModel(
            name='EOverTime',
            fields=[
                ('overtime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.overtime')),
            ],
            options={
                'abstract': False,
            },
            bases=('small_small_hr.overtime',),
        ),
        migrations.CreateModel(
            name='EStaffDocument',
            fields=[
                ('staffdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.staffdocument')),
            ],
            options={
                'abstract': False,
            },
            bases=('small_small_hr.staffdocument',),
        ),
        migrations.CreateModel(
            name='EStaffProfile',
            fields=[
                ('staffprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='small_small_hr.staffprofile')),
            ],
            options={
                'abstract': False,
            },
            bases=('small_small_hr.staffprofile',),
        ),
    ]
