# Generated by Django 3.1.2 on 2022-03-05 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
            options={
                'ordering': ['field_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('model', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Payment', 'Payment'), ('Company', 'Company')], max_length=10, null=True, verbose_name='Model')),
                ('fixed_values', models.BooleanField(default=False, verbose_name='Fixed values')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rrule', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, verbose_name='Recurring rule')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 5, 15, 36, 51, 230325), verbose_name='Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='This field is only considered, if the payment type has a recurring rule.', null=True, verbose_name='End of recurring period')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='core.estaffprofile', verbose_name='Employee')),
                ('extra_fields', models.ManyToManyField(blank=True, to='payment.ExtraField', verbose_name='Extra fields')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payment.paymenttype', verbose_name='Payment type')),
            ],
            options={
                'ordering': ['employee__user__first_name', '-date'],
            },
        ),
        migrations.AddField(
            model_name='extrafield',
            name='field_type',
            field=models.ForeignKey(help_text='Only field types with fixed values can be chosen to add global values.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_fields', to='payment.extrafieldtype', verbose_name='Field type'),
        ),
    ]
